name: Deploy OSRM to Cloudflare CDN

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OSRM dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y osrm-backend osrm-tools wget

    - name: Download OSM data
      run: wget http://download.geofabrik.de/your-region-latest.osm.pbf -O data.osm.pbf

    - name: Preprocess OSM data
      run: |
        osrm-extract -p /usr/share/osrm/profiles/car.lua data.osm.pbf
        osrm-partition data.osrm
        osrm-customize data.osrm

    - name: Upload to server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no data.osrm* $SSH_USER@$SSH_HOST:/var/www/html/osrm/
